unitary/quantum_chess/circuit_transformer.py
unitary/quantum_chess/circuit_transformer_test.py
unitary/quantum_chess/quantum_board.py

- Convert CircuitTransformer to use call to conform to Transformers
API.
- Convert SycamoreDecomposer to a free function that conforms to
Transformers API.
Continuation of ReCirq #276

Use new cirq transformer API for quantum_chess

---

unitary/quantum_chess/controlled_iswap.py

- Change deprecated optimizers with transformers.

Remove Deprecated optimizers

---

unitary/quantum_chess/circuit_transformer.py
unitary/quantum_chess/initial_mapping_utils.py

- device.qubit_set() is now device.metadata.qubit_set

Update some deprecated functions

---

unitary/quantum_chess/initial_mapping_utils.py

- As mentioned in #3, use graph_nx of the device
to construct adjacency dictionary.

Use networkx graph for computing adjacency

---

unitary/alpha/__init__.py
unitary/alpha/quantum_effect.py
unitary/alpha/quantum_effect_test.py
unitary/alpha/quantum_object.py
unitary/alpha/quantum_object_test.py
unitary/alpha/quantum_state.py
unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py
unitary/alpha/qubit_effects.py
unitary/alpha/qubit_effects_test.py
unitary/alpha/qudit_gates.py
unitary/alpha/qudit_gates_test.py

- Includes objects for:
- QuantumWorld (circuit)
- QuantumObject (qubit)
- QuantumEffect (gates)
Partial support for qutrits.

Initial Unitary Game API

---

unitary/alpha/README.md

- Explains how to do basic operations.

Add Readme tutorial for unitary alpha API

---

setup.py
unitary/alpha/quantum_effect_test.py

Test result behavior as well as expected circuit construction.

Better tests for anti-controls

---

unitary/alpha/quantum_effect.py
unitary/alpha/quantum_effect_test.py
unitary/alpha/quantum_object.py
unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py
unitary/alpha/qubit_effects_test.py
unitary/alpha/qudit_effects.py

- Add post-selection in order to implement pop()
- Add an effect_history in order to implement undo_last_move.

Add pop() and undo_last_effect()

---

README.md
unitary/alpha/__init__.py
unitary/alpha/qubit_effects.py
unitary/alpha/qubit_effects_test.py

I added the effect which corresponds to a move in quantum chess.

Add Move and PhasedMove effects.

---

unitary/alpha/README.md
unitary/alpha/quantum_effect.py
unitary/alpha/quantum_effect_test.py
unitary/alpha/qubit_effects.py
unitary/alpha/qubit_effects_test.py

- Beginners may find the if/then framework too confusing,
as it is not clear that the 'then' function can only take
a quantum effect and cannot have a classical imperative code.
- Changing this to apply as an experiment to see whether this
is easier to understand.
- This change also fixes some formatting that was not conformant with 'black'

Change quantum_if then() to apply()

---

unitary/alpha/quantum_effect_test.py
unitary/alpha/qudit_gates.py
unitary/alpha/qudit_gates_test.py

- Adds SwapPow and ISwapPow Gates for Qudits
- By default, this will do a swap and iswap gate for qudits.
- An exponent can be set to change this to do sqrt iswap and sqrt swap.

Adds qudit gates to unitary API

---

unitary/alpha/__init__.py
unitary/alpha/quantum_object.py
unitary/alpha/quantum_world_test.py
unitary/alpha/qudit_effects.py
unitary/alpha/qudit_effects_test.py
unitary/alpha/qudit_gates.py
unitary/examples/__init__.py
unitary/examples/tictactoe/__init__.py
unitary/examples/tictactoe/enums.py
unitary/examples/tictactoe/tic_tac_split.py
unitary/examples/tictactoe/tic_tac_split_test.py
unitary/examples/tictactoe/tic_tac_toe.py
unitary/examples/tictactoe/tic_tac_toe_test.py

- This PR contains an partial implementation of the Quantum TicTacToe.
- This contains a `QuantumEffect` for the quantum tic tac toe split move.
- It contains a `TicTacToe` board where you can place X and O and perform split moves.
Measurement is not yet completed.

Partial implementation of Quantum TicTacToe

---

unitary/examples/tictactoe/__init__.py
unitary/examples/tictactoe/enums.py
unitary/examples/tictactoe/tic_tac_split.py
unitary/examples/tictactoe/tic_tac_split_test.py
unitary/examples/tictactoe/tic_tac_toe.py
unitary/examples/tictactoe/tic_tac_toe_test.py

- Fix TicTacSplit to use sqrtSWAP(01) [or 02] instead
of sqrtSWAP of all states
- Measurements are implemented.
- Simple ASCII board to try it out.

More complete Quantum TicTacToe implementation

---

unitary/quantum_chess/controlled_iswap.py
unitary/quantum_chess/quantum_board.py

Re-add quantum chess commit #278 which was inadvertently squashed during import.
Fixes: #17

Update quantum chess code

---

unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py

raise ValueError if duplicate objects added

---

unitary/examples/tictactoe/ascii_board.py

- Add preliminary ASCII board for Quantum TicTacToe
- Displays probability for blank (.) and X and O.

Add ASCII board for Quantum TicTacToe board

---

unitary/examples/fox_in_a_hole/fox_in_a_hole.py

DO NOT MERGE YET
See Issue #21 before.

Reusing qobject after fix of #21

---

unitary/quantum_chess/quantum_board.py

The pawn capture circuit was changed since this was implemented.
See
https://quantum-realm-games.github.io/QuantumChessDocs/math.html#pawn-capture

Update pawn capture to new circuit

---

unitary/engine_utils.py
unitary/quantum_chess/ascii_board.py
unitary/quantum_chess/bit_utils.py
unitary/quantum_chess/circuit_transformer.py
unitary/quantum_chess/controlled_iswap.py
unitary/quantum_chess/experiments/circuit_transform_benchmark.py
unitary/quantum_chess/mcpe_utils.py
unitary/quantum_chess/move.py
unitary/quantum_chess/puzzles_test.py
unitary/quantum_chess/quantum_board.py
unitary/quantum_chess/quantum_moves.py

- cirq.Qid does not have a name, so changing to NamedQubit in typing.
- Also misc typing fixes all over.
- Remove gateset in engine.sampler, since it no longer exists in Cirq 1.0.

First batch of type issues from mypy

---

docs/quantum_chess/concepts.ipynb

This changed to optimize_for_target_gateset in Cirq 1.0.

Replace optimized_for_sycamore

---

docs/quantum_chess/concepts.ipynb

Should be cirq.optimize_for_target_gateeset not cirq_google.optimize_for_target_gateeset

Fix package name for optimize_for_target_gateset

---

unitary/examples/quantum_rpg/__init__.py
unitary/examples/quantum_rpg/enums.py
unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/qaracter_test.py

- This PR includes the initial Qaracter class (ie. Q-Character) that defines how a character's health points operate.
- Each Qaracter has one health point (HP) per qubit/QuantumObject.
- Each HP is initially unmeasured, and, once measured, determines whether that point is Healthy (1) or Hurt (0).

Initial Classes for Quantum RPG

---

unitary/examples/quantum_rpg/qaracter.py

The docstring still explains the `is_inactive` method.

Update Qaracter.is_active docstring after the latest change

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/npcs.py
unitary/examples/quantum_rpg/npcs_test.py
unitary/examples/quantum_rpg/qaracter.py

- Add class to actually run a Quantum RPG battle.
- This pits players versus NPCs in a battle.
- Player actions and NPC actions can be triggered via functions.
- Also adds a simple test NPC.
At this point, the MVP of the RPG is almost playable, though some work is needed to initialize and run the battle (plus make it more interesting).

Quantum RPG Battle Engine

---

unitary/alpha/__init__.py
unitary/alpha/qubit_effects.py
unitary/alpha/qubit_effects_test.py

- This PR adds an optional parameter to the Flip effect that allows a user to have a partial Flip.  This in effect is a X**t gate.
- This PR also adds a Phase effect, which is a Z**t gate (with default t=1).

Add effect_fraction and Phase effect

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/classes.py
unitary/examples/quantum_rpg/classes_test.py
unitary/examples/quantum_rpg/enums.py
unitary/examples/quantum_rpg/npcs.py
unitary/examples/quantum_rpg/npcs_test.py
unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/qaracter_test.py

- Reformatting changes only, done by running black on the quantum_rpg directory.

Formatting to new version of black.

---

unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py
unitary/alpha/qubit_effects.py
unitary/documentation_utils.py
unitary/engine_utils.py
unitary/engine_utils_test.py
unitary/examples/fox_in_a_hole/fox_in_a_hole.py
unitary/examples/fox_in_a_hole/fox_in_a_hole_test.py

- Should be just auto-format changes with the latest version of black formatting.

Reformat unitary files with new black version

---

docs/quantum_chess/concepts.ipynb

Apply suggestions from CommonTypos checker

---

unitary/examples/tictactoe/__init__.py
unitary/examples/tictactoe/enums.py
unitary/examples/tictactoe/tic_tac_toe.py
unitary/examples/tictactoe/tic_tac_toe_test.py

Creates a CLI for playing quantum tic tac toe to demonstrate the game.

Add tictactoe main function and gameplay

---

unitary/alpha/quantum_effect.py
unitary/alpha/quantum_world.py
unitary/alpha/qubit_effects.py
unitary/alpha/qubit_effects_test.py

- Allows comparison and printing of quantum effects
(Noticed this was missing when implementing qRPG)

Add str and equals to QuantumEffects

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/input_helpers.py
unitary/examples/quantum_rpg/input_helpers_test.py
unitary/examples/quantum_rpg/main_loop.py

- Adds one helper to translate a user input list into a lambda function.
- Adds a function to get a valid number choice from user input.
This will help in aiding input validation instead of crashing if bad input is entered.

Add helpers to aid in user input for Quantum RPG

---

unitary/examples/quantum_rpg/final_state_preparation/__init__.py
unitary/examples/quantum_rpg/final_state_preparation/classical_realm.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world_test.py
unitary/examples/quantum_rpg/item.py

- The first zone of the Final State Preparation RPG.
- This includes room descriptions and items.
- Characters can now walk around the starting 'frontier' between classical and quantum realms and explore the Oxtail university.
- The goal here would be to get the engineer from the NMR lab to join your party.
- Items trigering functions (such as the joining the party) as well as encounters, have not been done yet.

In the beginning was NMR

---

unitary/alpha/qubit_effects.py
unitary/alpha/qubit_effects_test.py

- Allow partial moves for fractional SWAP/ISWAP effects.

Add effect fraction for Move and PhasedMove

---

unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py

- Adds a way to copy the state of a QuantumWorld.

Add copy to QuantumWorld

---

unitary/examples/quantum_rpg/item.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/world.py

- This allows items to have functions that are callable and can modify game state.
- These will be useful for puzzles and for things that trigger new qaracters to the party, etc.

[Quantum RPG] Add functions to items

---

unitary/examples/quantum_rpg/final_state_preparation/classical_realm.py

- Adds encounters to the first zone (classical realm)
- Also fixes a few descriptions.

[Quantum RPG] Add encounters to first zone

---

requirements.txt
unitary/alpha/quantum_effect.py
unitary/alpha/quantum_world.py
unitary/engine_utils.py
unitary/examples/quantum_rpg/encounter.py
unitary/examples/quantum_rpg/final_state_preparation/classical_realm.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world_test.py
unitary/examples/quantum_rpg/game_state.py
unitary/examples/quantum_rpg/input_helpers.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/npcs.py
unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/qaracter_test.py
unitary/examples/quantum_rpg/world.py
unitary/examples/quantum_rpg/xp_utils.py
unitary/examples/tictactoe/tic_tac_split.py
unitary/quantum_chess/circuit_transformer.py
unitary/quantum_chess/quantum_board.py

- In preparation ofadding type checking to unitary,
fix errors reported by mypy.
- Mainly this is a lot of type casting and checking for None values.
- This is about half the type errors in unitary.

Initial type checking fixes 

---

unitary/examples/quantum_rpg/game_state.py
unitary/examples/quantum_rpg/input_helpers.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py

- Add load and save functionality to the main loop using the serialization provided in game state.
- Also adds a with_save_file() so we can load a save file without losing our place in the parsing of user input provided in tests.

[Quantum RPG] Add load and save to quantum RPG

---

unitary/examples/quantum_rpg/final_state_preparation/classical_realm.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world_test.py

In the NMR lab, talking to the engineer adds the
qaracter to the party.

[Quantum RPG] Add engineer to the party.

---

unitary/examples/quantum_rpg/README.md

Adding a readme.md.
Force pushing since we need a quick intro for people looking at the page.

Add Readme for intro.

---

unitary/examples/quantum_rpg/exceptions.py
unitary/examples/quantum_rpg/final_state_preparation/classical_frontier.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world_test.py
unitary/examples/quantum_rpg/final_state_preparation/hadamard_hills.py
unitary/examples/quantum_rpg/final_state_preparation/monsters.py
unitary/examples/quantum_rpg/final_state_preparation/oxtail_university.py
unitary/examples/quantum_rpg/item.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/world.py

- Add some more rooms and items
- Add bridge to next zone.
- With this PR, we should be good to go for a simple demo!

[Quantum RPG] Finish frontier zone

---

unitary/examples/quantum_rpg/bb84.py
unitary/examples/quantum_rpg/bb84_test.py

- Adds lasers for Alice and Bob to communicate via BB84.  Will be used for the puzzle for the
second zone.

[Quantum RPG] Add puzzle for Hadamard Hills

---

unitary/examples/quantum_rpg/bb84.py
unitary/examples/quantum_rpg/bb84_test.py
unitary/examples/quantum_rpg/final_state_preparation/hadamard_hills.py

- Add BB84 puzzle for the Hadamard Hills.
- Take two.  The previous PR somehow got screwed up.

[Quantum RPG] Hadamard Hills Puzzle

---

unitary/examples/quantum_rpg/ascii_art.py
unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/qaracter.py

- This comand allows you to see your party and their circuits.

[Quantum RPG] Add status command

---

unitary/examples/quantum_rpg/ascii_art.py
unitary/examples/quantum_rpg/xp_utils.py
unitary/examples/quantum_rpg/xp_utils_test.py

- Once the number of operations on each qubit exceeds your level, you will gain another level (and HP)

[Quantum RPG] Gaining a level

---

unitary/examples/quantum_rpg/bb84.py
unitary/examples/quantum_rpg/bb84_test.py
unitary/examples/quantum_rpg/final_state_preparation/classical_frontier.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world_test.py
unitary/examples/quantum_rpg/final_state_preparation/hadamard_hills.py
unitary/examples/quantum_rpg/final_state_preparation/quantum_perimeter.py

- When you type the password, the door unlocks!

[Quantum RPG] Add puzzle door to Hadamard Hills

---

unitary/alpha/quantum_world.py
unitary/engine_utils.py
unitary/examples/fox_in_a_hole/fox_in_a_hole.py
unitary/examples/quantum_chinese_chess/enums.py
unitary/examples/quantum_chinese_chess/enums_test.py
unitary/examples/quantum_chinese_chess/test_utils.py
unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/item.py
unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/xp_utils.py
unitary/examples/tictactoe/enums.py
unitary/examples/tictactoe/tic_tac_toe.py
unitary/examples/tictactoe/tic_tac_toe_test.py
unitary/quantum_chess/caching_utils.py
unitary/quantum_chess/circuit_transformer.py
unitary/quantum_chess/initial_mapping_utils.py
unitary/quantum_chess/pauli_decomposition.py
unitary/quantum_chess/quantum_board.py
unitary/quantum_chess/swap_updater.py

- Clean up formatting and typing issues in advance of adding additional CI tests.

[Unitary] Formatting and typing fixes

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/final_state_preparation/classical_frontier.py
unitary/examples/quantum_rpg/main_loop_test.py

- Get rid of spammy "X is DOWN" message for enemies and just skip it.
- Get rid of debug print statement
- Add a enemy number for more clear input.

[Quantum RPG] Some small text improvements

---

unitary/examples/quantum_rpg/final_state_preparation/hadamard_hills.py
unitary/examples/quantum_rpg/final_state_preparation/monsters.py

- Add room descriptions and encounters.

[Quantum RPG] Finish Hadamard Hills Zone

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/final_state_preparation/hadamard_hills.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/npcs.py
unitary/examples/quantum_rpg/npcs_test.py

- Add Schrodinger Cat as the final boss for the Hadamard Hills.

[Quantum RPG] Nice kitty, good kitty

---

unitary/examples/quantum_rpg/final_state_preparation/monsters.py
unitary/examples/quantum_rpg/xp_utils.py

- Two small issues encountered during testing:
- _purple_foam accidentally returning RedFoam
- Awarded XP message even if no xp was awarded.

[Quantum RPG] Small bug fixes

---

unitary/examples/quantum_rpg/classes.py

Fix broken engineer level 3 H attack

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/classes.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/npcs_test.py

- Add unit test for level 3 qaracters to make sure descriptions are
there.
- Also, change help to "?" since "h" is used for Hadamard already.

[Quantum RPG] Add unit test for Level 3 Qaracters

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py

- Multiple testers have been confused about the end of the battles, as they end abruptly with little information.
- I have added a battle summary that explains what happened and that status of all combatants.

[Quantum RPG] Battle summary

---

unitary/examples/quantum_rpg/final_state_preparation/hadamard_hills.py

- Bug where bookshelves could not be examined.

[Quantum RPG] Fix examine bookshelf

---

unitary/examples/quantum_rpg/README.md

- Add more to the README about how to install and play the game.

[Quantum RPG] Add information on how to play

---

dev_tools/check_notebooks.py
dev_tools/write-ci-requirements.py
unitary/examples/quantum_rpg/xp_utils.py
unitary/examples/quantum_rpg/xp_utils_test.py

[Quantum RPG] Display qaracter sheet during XP

---

unitary/examples/quantum_rpg/final_state_preparation/oxtail_university.py

Fixed typos identified by @strilanc

[Quantum RPG] Fix typos

---

unitary/examples/quantum_rpg/final_state_preparation/hadamard_hills.py

The west hill has a receiver, but the guy there describes working on the transmitter, and vice versa with the east hill. Swap the NPCs to make it match up.

[RPG] swap West/East Hut physicists

---

unitary/alpha/__init__.py
unitary/alpha/quantum_effect_test.py
unitary/alpha/quantum_object.py
unitary/alpha/qubit_effects.py
unitary/alpha/qudit_effects.py

- Generalize Flip and Cycle to take quantum objects of any dimensions.
- Will follow up with changing references to QuditCycle over in the next PR.

Refactor Flip and Cycle to take any dimensions

---

docs/unitary/getting_started.ipynb
docs/unitary/physics_terms.md

- Caught by an internal typo checker.

Fix common typos.

---

examples/quantum_rpg/main_loop_test.py
examples/quantum_rpg/world.py

sort exists for printing

---

unitary/alpha/quantum_effect_test.py
unitary/alpha/quantum_world.py
unitary/alpha/qubit_effects.py
unitary/alpha/qubit_effects_test.py
unitary/alpha/qudit_gates.py
unitary/alpha/qudit_gates_test.py

(This is a re-submit of PR#190)
- Add generalized Hadamard gate into qudit_gates and qudit_effects
- Fix a few typos in qudit_gates and qudit_effects

Add generalized Hadamard gate

---

dev_tools/check_notebooks.py
dev_tools/pylint_copyright_checker.py
examples/quantum_chinese_chess/enums.py
examples/quantum_rpg/final_state_preparation/final_state_world_test.py
examples/tic_tac_toe/tic_tac_toe.py
unitary/quantum_chess/swap_updater.py

It seems that some of the files have not been run through the formatter (black) for some time. There are no functional changes in this commit; the changes are merely the result of running 'black' on all the files.

Reformat Python files that need formatting

---

.github/workflows/first-interaction.yaml

- Don't need to check out a copy of the repo
- Use the correct YAML multiline format character
- Don't run for Dependabot

Multiple minor fixes to first interactions greetings workflow
