unitary/alpha/README.md
unitary/alpha/quantum_effect.py
unitary/alpha/quantum_effect_test.py

There needs to be an X gate after the control gate to put the
qubit back in the original state.
Also adds some documentation to quantum if/then classes.

Fix anti-controls

---

unitary/alpha/README.md

- Add note that peek() with no arguments defaults to sampling
the whole board.
- Add a note that quantum_if effects can only apply to
quantum effects and use the fancy term Stinespring's dilation.

Add readme to clarify peek() and quantum_if behavior.

---

docs/_toc.yaml

An included toc file must start with `toc:` as the first line.

Add missing "toc:"

---

unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py

- This PR fixes post-selection and reuse of qubits.
- Now, after a pop(), the qubit is replaced by a new qubit that is
initialized to the value of the measurement, and the old qubit
is moved to an ancilla and post-selected on.
- This PR also includes a force_measurement() function, that can
be used to force a measurement of a particular outcome (for instance,
in replaying a game).
Fixes:#21

Fix post-selection and re-use of popped qubits.

---

unitary/quantum_chess/controlled_iswap_test.py
unitary/quantum_chess/swap_updater_test.py

Addressing breaking change upstream (Cirq): https://github.com/quantumlib/Cirq/pull/5426

Adds explicit precision to tests.

---

unitary/examples/tictactoe/__init__.py
unitary/examples/tictactoe/ascii_board.py
unitary/examples/tictactoe/enums.py
unitary/examples/tictactoe/tic_tac_split.py
unitary/examples/tictactoe/tic_tac_split_test.py
unitary/examples/tictactoe/tic_tac_toe.py
unitary/examples/tictactoe/tic_tac_toe_test.py

This PR includes some small additions, notably the ability to choose a ruleset (CLASSICAL vs MINIMAL QUANTUM vs FULLY QUANTUM). The default is FULLY QUANTUM, so running this as before ('python ascii_board.py') does not change any of the previous gameplay. The PR also includes the option for arguments (and has a -h with a minimal description of the game + usage).

Expanding the TicTacToe example to make it a little more like TiqTaqToe

---

unitary/quantum_chess/controlled_iswap.py
unitary/quantum_chess/swap_updater.py

- Get rid of references to optimizers
- Copy one function over that was removed in the deprecation process.

Upgrade Quantum Chess to Cirq 1.0

---

unitary/quantum_chess/quantum_board.py
unitary/quantum_chess/quantum_board_test.py
unitary/quantum_chess/quantum_moves.py

See
https://quantum-realm-games.github.io/QuantumChessDocs/rules.html#basic-en-passant
The circuits were redesigned after the Python implementation was
written.

Implement new en passant circuits

---

unitary/quantum_chess/quantum_board.py
unitary/quantum_chess/quantum_board_test.py
unitary/quantum_chess/quantum_moves.py

In some cases the slide target qubits or the merge source qubits were swapped. This doesn't work because the circuits aren't symmetrical. So it's necessary to add additional circuits for the mirror-image versions.

Fix split/merge slide circuits

---

unitary/quantum_chess/quantum_board.py
unitary/quantum_chess/quantum_board_test.py

Squares measured as 0% or 100% occupied may actually be in a superposition due to noisy measurements (see commit message for more detail).

[Chess] Improve behavior on some edge cases

---

dev_tools/write-ci-requirements.py
requirements.txt
unitary/alpha/__init__.py
unitary/alpha/quantum_effect_test.py
unitary/alpha/quantum_object_test.py
unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py
unitary/alpha/qubit_effects_test.py
unitary/alpha/sparse_vector_simulator.py
unitary/alpha/sparse_vector_simulator_test.py
unitary/examples/fox_in_a_hole/fox_in_a_hole.py

Add a sparse state vector simulator which can be used as the sampler for a QuantumWorld. This speeds up simulation for circuits which use only a tiny fraction of the 2^n possible states. In addition to calculating on only the used states instead of all states, a post-selection operator is inserted into circuits when performing a measurement using the sparse simulator, which prunes the states not conforming with the measurement outcome.
Not sure what kind of unit tests we might want for sparse_vector_simulator. Is there like a standard test suite for Cirq simulators?

Sparse state vector simulator

---

unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py

This change utilizes the existing used_object_keys internal bookkeeping structure to return the object with a given name.

Add get_object_by_name to QuantumWorld

---

unitary/examples/quantum_rpg/classes.py
unitary/examples/quantum_rpg/classes_test.py

- This PR adds two very simple player classes to the quantum RPG.
- This PR is advance of a feature that can demonstrate an example battle.

Add two example player classes to Quantum RPG

---

unitary/examples/quantum_rpg/item.py
unitary/examples/quantum_rpg/item_test.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/world.py
unitary/examples/quantum_rpg/world_test.py

- Add items you can interact with in Quantum RPG.
- These will be useful for signs, helpful NPCS, and puzzles.
- Right now, they can only print out a string.
Follow-up PRs will hook in custom functions for more complicated puzzles.  For right now, there is a untyped 'Callable' as a placeholder for such customizations until I figure out what the function signature should be (or maybe it will be a class, like ItemAction).

Add items to Quantum RPG

---

unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/qaracter_test.py

- Currently, add_quantum_effect only takes one qubit.
- This allows you to pass a variable amount of qubits into the function so that we can add two-qubit gates.

Quantum RPG: Allow multi-qubit effects in qaracters

---

unitary/examples/quantum_rpg/ascii_art.py
unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/encounter.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/game_state.py
unitary/examples/quantum_rpg/game_state_test.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/npcs_test.py
unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/qaracter_test.py
unitary/examples/quantum_rpg/xp_utils.py
unitary/examples/quantum_rpg/xp_utils_test.py

- Add a game state object that contains state for the main loop.
- This allows us to store the user_input and output source, so we don't have to pass them around all over.
- This also adds a state_dict where we can store random state, so that we can have some puzzles with state.
- This also contains a serialization mechanism, so we can have a way to generate 1990's style game codes.

Add Game State to Quantum RPG

---

unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/npcs.py
unitary/examples/quantum_rpg/npcs_test.py

- Adds Quantum Foam monsters to quantum RPG
- Also reorganizes some of the NPC functions for code reuse.

Add NPCs to Quantum RPG

---

unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/qaracter_test.py

- This adds effect fraction to two qubit operations for save files
- Also adds a test for two-qubit operations (note that Split/PhasedSplit) involve a sqrt SWAP/ISWAP so this tests effect fraction)

[Quantum RPG] Add effect fraction to save file

---

unitary/alpha/quantum_world.py
unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/encounter.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/qaracter_test.py

- Copy the party when entering a battle so that temporary battle effects, like gates added to the circuit or measurements, do not affect the qaracters once the battle is over.

[Quantum RPG] Copy qaracters during battles

---

unitary/examples/quantum_rpg/final_state_preparation/classical_realm.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/npcs.py
unitary/examples/quantum_rpg/npcs_test.py

Fix a few bugs and issues found when running the RPG game.
- Slime parameter is mainly used for deterministic unit tests.
However, if not specified, it would generate a KeyError.
Change to get() to avoid this exception.
- main loop should pass game state to award XP and not party.
- Tweak a few descriptions that had typos or looked funny.

[Quantum RPG] Fix a few bugs and issues

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/classes.py
unitary/examples/quantum_rpg/classes_test.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/main_loop_test.py

Now, the qaracter actions are explained, such as:
`s) Sample enemy qubit.`
There is also a help option within the battle.

[Quantum RPG] Add help and descriptions to qaracter actions

---

unitary/examples/quantum_rpg/final_state_preparation/classical_frontier.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world.py
unitary/examples/quantum_rpg/final_state_preparation/monsters.py
unitary/examples/quantum_rpg/final_state_preparation/oxtail_university.py

Reorganize room descriptions in quantum RPG
-  Splits monsters and the first zone into two.

Reorganize room descriptions in quantum RPG

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py

- Change status lines to fixed format to improve the alignment.  Otherwise, short or long names can throw off the alignment of the status line.
- Also adds a text message explaining what happened if the players or enemies escape the battle.

[Quantum RPG] Improve text formatting

---

unitary/examples/quantum_rpg/battle.py
unitary/examples/quantum_rpg/battle_test.py
unitary/examples/quantum_rpg/encounter_test.py
unitary/examples/quantum_rpg/final_state_preparation/oxtail_university.py
unitary/examples/quantum_rpg/game_state.py
unitary/examples/quantum_rpg/game_state_test.py
unitary/examples/quantum_rpg/main_loop_test.py
unitary/examples/quantum_rpg/npcs.py

- Adds an in-game help option for a quantopedia.
- When you find the book or item that has info on the type of enemy you are facing, you can type 'q' and learn about it.

[Quantum RPG] Quantopedia

---

unitary/examples/quantum_rpg/main_loop.py
unitary/examples/quantum_rpg/main_loop_test.py

- Look command displays the location again. (takes lowest precedence in case there is something to look at in the room.)

[Quantum RPG] Add LOOK command

---

unitary/examples/quantum_rpg/qaracter.py
unitary/examples/quantum_rpg/xp_utils.py
unitary/examples/quantum_rpg/xp_utils_test.py

It is confusing how the status display doesn't show qubits that don't have any effects on them. To fix this, specify a qubit order for the diagram, which allows us to force unused qubits to be included.

Fix status display for qubits with no effects

---

docs/unitary/overview.md

Create the overview of unitary from the document created by @cognigami

[Unitary] Create overview.md

---

unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py

Allows strings to be passed to peek() and pop()
Also returns the object when world["name"] is called.

Allow strings to be passed as subscripts or to peek/pop in QuantumWorld

---

unitary/examples/quantum_chinese_chess/board.py
unitary/examples/quantum_chinese_chess/board_test.py
unitary/examples/quantum_chinese_chess/move.py
unitary/examples/quantum_chinese_chess/move_test.py

- Update flying general check to include the cases where there are quantum pieces between two kings(aka generals).
- Update Move to not depend on Board to break the cyclic dependency.

[Quantum Chinese Chess] Update flying general check

---

unitary/alpha/quantum_effect.py
unitary/examples/quantum_chinese_chess/chess.py
unitary/examples/quantum_chinese_chess/move.py
unitary/examples/quantum_chinese_chess/move_test.py

Implement the following types of moves:
- slide
- split slide
- merge slide
- cannon fire

[Quantum Chinese Chess] Implement more move types

---

unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py
unitary/examples/quantum_chinese_chess/chess.py
unitary/examples/quantum_chinese_chess/chess_test.py

- Add save_snapshot() and restore_last_snapshot() to QuantumWorld
- Apply these new methods in quantum chinese chess

[Quantum Chinese Chess] Add save_snapshot() and restore_last_snapshot() to QuantumWorld

---

unitary/alpha/quantum_world.py
unitary/engine_utils.py
unitary/examples/quantum_rpg/ascii_art.py
unitary/examples/quantum_rpg/classes.py
unitary/examples/quantum_rpg/input_helpers.py
unitary/quantum_chess/quantum_board.py

This PR fixes formatting everywhere.

fixed formatting

---

unitary/examples/quantum_rpg/final_state_preparation/classical_frontier.py
unitary/examples/quantum_rpg/final_state_preparation/final_state_world_test.py

This change hints to the user to examine the bridge to learn if it's broken. Examining the bridge effectively restores its state from previous sessions.
Prior to this change, the state of the bridge would not get persisted in the save file, and the user (with the engineer) would need to fix it whenever it loaded the game back.
This approach provides slightly better continuity, and is implemented within the constraints of the current framework.

[Quantum RPG] Restore bridge repair upon examining the bridge

---

unitary/quantum_chess/quantum_board_test.py
unitary/quantum_chess/test_utils.py

See 2nd commit message for an example.

[Quantum Chess] Improve test failure output

---

unitary/examples/quantum_chinese_chess/board.py
unitary/examples/quantum_chinese_chess/board_test.py
unitary/examples/quantum_chinese_chess/chess.py
unitary/examples/quantum_chinese_chess/chess_test.py
unitary/examples/quantum_chinese_chess/enums.py
unitary/examples/quantum_chinese_chess/enums_test.py
unitary/examples/quantum_chinese_chess/piece_test.py

- Print the board with sampled probabilities.
- For proper print, different treatment is made for English vs Chinese and Sublime terminus vs mac/gLinux terminal.

[Quantum Chinese Chess] Improve chess board printing

---

examples/quantum_rpg/main_loop.py
examples/quantum_rpg/main_loop_test.py
examples/quantum_rpg/npcs.py

Fixes #177
Output looks like this:
```
>qua
Observer
Observers are known to frequent quantum events.
They will measure qubits in order to find out their values.
BlueFoam
Blue foam are the simplest kind of quantum errors.  Blue foam
are usually found in the |0> state and can be measured.
They will often slime their opponents with small fracts of X gates.
GreenFoam
Green foam are a simple kind of quantum error.  Green foam
are usually found in the |0> state and can be measured immediately.
They will often ooze, which will change their opponent's phase
RedFoam
Red foam are a slightly more dangerous type of quantum error.
They are usually found in the |1> state and must be flipped
before they can be safely measured.
PurpleFoam
Purple foam are a combination of red and blue form.
They are found …
```

implemented quantopedia command

---

examples/quantum_rpg/bb84_test.py
examples/quantum_rpg/main_loop.py
examples/quantum_rpg/main_loop_test.py

Quit command is matched first before user input is lower-cased.

Make Quit case-sensitive

---

unitary/alpha/qudit_effects.py
unitary/alpha/qudit_gates.py
unitary/alpha/qudit_gates_test.py

(This is a re-submit of PR#191)
- update qudit_gates.py, especially the way unitary matrices are calculated;
- add a few tests in qudit_gates_test.py;
- update comments in qudit_effects.py.

Update qudit gates and tests

---

examples/quantum_rpg/final_state_preparation/final_state_world_test.py
examples/quantum_rpg/final_state_preparation/quantum_perimeter.py

- A layout and some room descriptions for the next RPG zone.  Based on the Perimeter Institute in Waterloo.
- Based on the quantum AI road map, the next zone should enter tunnels under the mountains:
https://quantumai.google/learn/map

Preliminary draft of the Perimeter zone

---

examples/fox_in_a_hole/fox_in_a_hole.py
examples/fox_in_a_hole/fox_in_a_hole_test.py

- Add lots of comments and clean up some code paths
- Hopefully should make it easier to understand.

Clean up fox-in-a-hole

---

unitary/alpha/quokka_sampler.py
unitary/alpha/quokka_sampler_test.py

- This sampler converts circuits to QASM and then sends them to a quokka endpoint for simulation.
- Any parameterized circuits are resolved and sent point by point to the device.

Add support for sampling from Quokka devices

---

.github/workflows/pylint.yml
setup.py

This is needed for internal documentation tool.
All unit tests pass with Python 3.10.
Also restrict the CI check to use pylint-2 as
a temporary workaround for #210.

Allow installation to Python 3.10 environment

---

.github/workflows/black.yml
.github/workflows/pylint.yml
.github/workflows/pythonpackage.yml

CI - update GitHub actions to node20
Address deprecation warnings in CI workflow annotations at
https://github.com/quantumlib/unitary/actions/runs/11221964643
Namely update to
* actions/checkout@v4 per https://github.com/actions/checkout/blob/main/CHANGELOG.md
* actions/setup-python@v5 per https://github.com/actions/setup-python/releases/tag/v5.0.0

CI - update GitHub actions to node20

---

dev_tools/.pylintrc
examples/fox_in_a_hole/fox_in_a_hole.py
examples/quantum_chinese_chess/board.py
examples/quantum_chinese_chess/board_test.py
examples/quantum_chinese_chess/chess.py
examples/quantum_chinese_chess/move.py
examples/quantum_chinese_chess/move_test.py
examples/quantum_rpg/bb84_test.py
examples/quantum_rpg/final_state_preparation/final_state_world_test.py
examples/quantum_rpg/main_loop.py
examples/quantum_rpg/main_loop_test.py
examples/quantum_rpg/qaracter.py
unitary/alpha/quantum_world.py
unitary/alpha/quantum_world_test.py
unitary/alpha/qudit_gates_test.py
unitary/alpha/quokka_sampler.py
unitary/engine_utils.py
unitary/engine_utils_test.py
unitary/quantum_chess/mcpe_utils.py
unitary/quantum_chess/mcpe_utils_test.py
unitary/quantum_chess/quantum_board.py
unitary/quantum_chess/quantum_board_test.py
unitary/quantum_chess/swap_updater.py
unitary/quantum_chess/swap_updater_test.py

- fix wildcard-import and unused-wildcard-import
- fix unused-variable
- fix unnecessary-pass and format
- fix redefined-builtin
- fix anomalous-backslash-in-string
- fix consider-using-f-string
- fix dangerous-default-value
Partially addresses #210

pylint - partial fix up

---

CONTRIBUTING.md

Fix errors about the development processes that were made in the recent changes to `CONTRIBUTING.md` in PR #216.

Fix errors in CONTRIBUTING.md

---

.github/workflows/black.yml
.github/workflows/pylint.yml
.github/workflows/pythonpackage.yml

Google's security practices for GitHub Actions states the following:
> When using a third-party action (one not hosted in a [Google-managed org](http://go/github/orgs)), a fixed version of the action MUST be used by [specifying a specific commit](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses), rather than a branch like "main", or a tagged release, which can be overwritten by any maintainer of the action.
This commit adds sha hash numbers to all `uses:` directives that didn't have one already. This was done by running the tool [frizbee](https://github.com/stacklok/frizbee?README) over the files.
In addition, it does the following other best-practices changes:
- pin versions of runners instead of using …

Pin versions & make other changes to CI workflows for best practices

---

dev_tools/nbfmt
dev_tools/pylint

This fixes minor warnings from shellcheck in two of the shell scripts in dev_tools/.

Fix tiny warnings from shellcheck

---

dev_tools/format-incremental

This is a rewritten version of Cirq's `check/format-incremental` script. Changes:
- Added a `--help` option
- Added a `--no-color` option
- Added a `--quiet` option
- Make the script more robust in various ways (e.g., declare variables, be more careful in parsing CLI arguments, etc.)
- Don't hard-code ANSI color code sequences in every echo statement
- Make the script more DRY
- Revise the error & info messages to try to be slightly more clear
A motivation for making these changes is to produce an updated, somewhat more user-friendly version of `format-incremental` that can be used in all Quantumlib repos, including for new projects/repos that are being planned in the near future.

Add format-incremental script

---

docs/quantum_chess/concepts.ipynb

- Long-standing bug from a feedback about missing links on what ISWAP and sqrt-ISWAP gates were for those that were unfamiliar but interested in quantum chess.

Add supporting links for ISWAP and other gates
